import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import BodyWithTheme from "@/components/BodyWithTheme";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <BodyWithTheme><AuthProvider>{children}</AuthProvider></BodyWithTheme>
        </ThemeProvider>
      </body>
    </html>
  );
}